name: ShountDown
main: de.dorsax.ShountDown.Main
version: "0.9"
api-version: "1.15"
author: dor_sax

commands:
    shutdown:
        description: Shut down with a timer
        usage: /<command> -abort -comment "Comment here" -time <Minutes or HH:MM> --whitelist --silent
        permission: shountdown.shutdown
    reboot:
        description: Reboot with a timer
        usage: /<command> -abort -comment "Comment here" -time <Minutes or HH:MM> --whitelist --silent
        permission: shountdown.reboot
permissions:
    shountdown.*:
        children:
            shountdown.shutdown: true
            shountdown.reboot: true
        default: op
    shountdown.shutdown:
        default: false
    shountdown.reboot:
        default: false